{% set version = load_file_regex(load_file='VERSION', regex_pattern='^[0-9.]+$') %}

package:
  name: tangods_moenchcontrol
  version: {{ version.string }}

source:
  path: ../
build:
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"
  number: 0
requirements:
  build:
    - python
    - setuptools
  run:
    - python>=3.10
    - pytango>=9.3.6
    - slsdetlib
    - slsdet
    - bidict>=0.22.1
    - numpy>=1.24.1

about:
  home: https://github.com/MBI-Div-B/pytango-moenchDetectorControl
  license: MIT
  summary: "tangoDS control for PSI moench detector"
  description: control server for a moench detector with tango DeviceServer
  dev_url: https://github.com/MBI-Div-B/pytango-moenchDetectorControl
  doc_url: https://github.com/MBI-Div-B/pytango-moenchDetectorControl/blob/main/README.md

