{% set data = load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True) %}

package:
  name: controlmoenchtangods
  version: {{ data.get('version') }}

source:
  path: ../
build:
  # entry_points:
  #   - MoenchControlServer = controlmoenchtangods:main
  script: "{{ PYTHON }} -m pip install . -vv"
requirements:
  build:
    - python
    - setuptools
  run:
    - python>=3.10
    - pytango>=9.3.6
    - slsdetlib==6.1.2 # [linux-64]
    - slsdet==6.1.2 # [linux-64]
    - bidict>=0.22.1
    - numpy>=1.24.1

about:
  home: https://github.com/lrlunin/pytango-moenchZmqServer
